### ISSUE TITLE
This doesn't work when I have tabs pinned.  I keep my email tab pinned and I must change the pinned tab, which is essentially the first tab to the container that I want to use on all tabs.  Is there a way to IGNORE pinned tabs? 

### ISSUE THREAD

**Issue by kstev99** [chronakis/firefox-sticky-window-containers#16]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by chronakis** [comment]
Hello,

It indeed takes the first tab's container, pinned or not, as the default container for the window. I am afraid this add-on came from my own needs and my first tab in each window is a google mail tab. One window has my home email and container, the other my work email and container.

If I understand you correctly you would like the pinned tabs to be ignored and set the window container by the first non-pinned tab? I think this is not difficult to implement in itself but it may require more work that I have time for to add some settings.

Please confirm that this is what you want and I will have a look if I can use about:config for configuration.

Yiannis

**Comment by kstev99** [comment]
Yes originally that was my request, to ignore the pinned tabs.  I was just confused at first when the extension wasn't working.  Once I figured out that the first tab IS the FIRST tab, pinned or not, I actually sort of like it that way.  I would just leave things the way that they are and close this issue unless you want to add an option to ignore pinned tabs.  Thank  you for the reply and taking the time to create this add-on

**Comment by chronakis** [comment]
Oh, that's very nice to know :)

I will indeed close it and leave it as is.

Thank you!
