### ISSUE TITLE
Infinite loop when 1st tab container is Facebook or Twitter

### ISSUE THREAD

**Issue by kennu** [chronakis/firefox-sticky-window-containers#3]
When the first tab in the window has been opened in a Facebook Container or a Twitter Container, opening a new tab causes an infinite loop. I'm guessing it's because the Facebook Container and Twitter Container plugins are trying to prevent running any other URLs in the same container.

**Comment by chronakis** [comment]
Thanks for reporting this. Indeed it happnes with the first tab on facebook and opening second to a non facebook url.

The sticky extension tries to switch the new tab to the facebook container. But the facebook container, if it detects a non facebook url, it will switch the tab to the default container which will trigger the circle again.

I tried to fix this a while ago by excluding the facebook container but got stuck into something. I will have another go with the first

**Comment by chronakis** [comment]
A fix for this is now committed and very soon I will upload the new release. Thank you for your patience!

**Comment by kennu** [comment]
Awesome :)

**Comment by chronakis** [comment]
@kennu Thanks!
